name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
      - master

env:
  PROJECT_VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      env:
        MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"
      run: mvn clean package -DskipTests

    - name: Rename JAR
      run: mv target/*.jar target/helloworld-${{ env.PROJECT_VERSION }}.jar
